export default {
 TRANSLATE: {
  memberManager: "Quản lý thành viên",
  chargeCointsToMember: "Quản lý nạp coints",
  heyCareAuthenApprove: "Xác thực thành viên",
  heyCareListOrder: "Danh sách đơn",
  heyCareOrder: "Xem đơn",
  heyCareOrderManager: "Quản lý đơn",
  heyCareJob: "Xem ca",
  heyCareJobManager: "Quản lý ca",
  heyCareFeedbackManager: "Phản hồi",
  heyCareRevenue: "Xem doanh thu",
  heyCareStatistic: "Thống kê tổng quan",
  heyCareJobAssign: "Gán đơn",

  cleaningAuthenApprove: "Xác thực thành viên giúp việc",
  cleaningListOrder: "Danh sách đơn giúp việc",
  cleaningOrder: "Xem đơn giúp việc",
  cleaningOrderManager: "Quản lý đơn giúp việc",
  cleaningJob: "Xem ca giúp việc",
  cleaningJobManager: "Quản lý ca giúp việc",
  cleaningFeedbackManager: "Phản hồi giúp việc",
  cleaningRevenue: "Xem doanh thu giúp việc",
  cleaningStatistic: "Thống kê tổng quan giúp việc",
  cleaningJobAssign: "Gán đơn giúp việc",
  cleanStatistic: "Thống kê Hey-Clean",

  memberBlock: "Khóa tài khoản",
  memberUnblock: "Mở khóa tài khoản",
  jobFeedback: "Công việc đánh giá & phản hồi",
  hospitalManager: "Quản lý bệnh viện",
  userManager: "Quản lý tài khoản",
  partnerManager: "Quản lý đối tác",
  lecture: "Quản lý bài đào tạo",
  hotnewManager: "Quản lý HotNews",

  pushallstaff: "Push All Staff",
  promoteToMemberHeyClean: "Tặng mã KM Clean",
  priceIncreasesHeyCare: "Nhân giá chăm sóc",
  priceIncreasesHeyClean: "Nhân giá dọn dẹp",
 },
 MEMEBER_ROLES: ["memberManager", "heyCareAuthenApprove", "memberBlock", "memberUnblock", "cleaningAuthenApprove", "promoteToMemberHeyClean"],
 ORDER_ROLES: ["heyCareListOrder", "heyCareOrder", "heyCareOrderManager", "cleaningListOrder", "cleaningOrder", "cleaningOrderManager"],
 ORDER_JOB_ROLES: ["heyCareJob", "heyCareJobManager", "heyCareJobAssign", "cleaningJob", "cleaningJobManager", "cleaningJobAssign", "pushallstaff"],
 FEEDBACK_ROLES: ["heyCareFeedbackManager", "cleaningFeedbackManager", "jobFeedback"],
 STATISTIC_ROLES: ["heyCareRevenue", "heyCareStatistic", "cleaningRevenue", "cleaningStatistic", "cleanStatistic"],
 SYSTEM_ROLES: ["userManager", "hospitalManager", "partnerManager", "lecture", "hotnewManager", "priceIncreasesHeyCare", "priceIncreasesHeyClean"],
}
