export default {
 JOB_LOG_TYPE: {
  CREATE: 0,
  REGISTER: 1,
  NOTE: 2,
  MOVE_TO_PENDING: 3,
  RELEASE: 4,
  TRANSFER: 5,
  MOVE_TO_PROCESS: 6,
  DONE: 7,
 },

 JOB_STATUS: {
  WAIT_FOR_PROCESS: 0,
  PROCESSING: 1,
  FINISH: 2,
  PENDING: 3,
 },

 CANCEL_FEEDBACK_REASON: {
  DELAY: "Chờ lâu mà chưa có Tài xế nhận đơn",
  CUSTOMER_REJECT: "Khách hủy đơn/Shop hết hàng",
  CHANGE_INFO: "Thay đổi thông tin đơn hàng",
  SHIPPER_NOT_ARRIVE: "Tài xế không tới lấy hàng",
  SHIPPER_NHO_HUY: "Tài xế nhờ hủy",
  PAYMENT: "Tôi gặp vấn đề khi thanh toán đơn hàng",
  others: "Lý do khác",
 },

 FEEDBACK_REASON: {
  CANNOT_CALL: "Tôi không liên lạc được với tài xế",
  DELAY: "Tài xế giao hàng chậm",
  NOT_ARRIVE: "Tài xế không đến lấy hàng",
  CHEAT_MONEY: "Tài xế thu thêm tiền",
  NOT_FOUND: "Tôi không tìm được tài xế cho đơn hàng",
  CANNOT_CONTACT: "Tôi không liên lạc được với tài xế/shop",
  WRONG_UPDATE: "Tài xế cập nhật sai trạng thái đơn hàng",
  REJECT_SHOP: "Tôi không huỷ được đơn hàng",
  WRONG_DISTANCE: "Đơn hàng bị tính sai khoảng cách",
  WRONG_MONEY: "Đơn hàng sai giá",
  DENY: "Khách không nhận đơn hàng",
  BREAK: "Hàng của tôi bị hỏng trong quá trình vận chuyển",
  PAYMENT: "Tôi gặp vấn đề khi thanh toán đơn hàng",
  NOT_ARRIVE_BIKE: "Tài xế không đến đón tôi",
  NOT_FOUND_BIKE: "Tôi không tìm được tài xế",
  REJECT_SHOP_BIKE: "Tôi không huỷ được chuyến đi",
  WRONG_DISTANCE_BIKE: "Chuyến đi bị tính sai khoảng cách",
  WRONG_MONEY_BIKE: "Chuyến đi sai giá",
  PAYMENT_BIKE: "Tôi gặp vấn đề khi thanh toán chuyến đi",
  CANNOT_FIND_SHOP: "Tôi không tìm thấy địa chỉ shop",
  REJECT_SHIPPER: "Admin huỷ giúp tôi đơn hàng",
  PENDING: "Hỗ trợ chuyển trạng thái chờ giao",
  NOT_FOUND_RECEIVER: "Tôi không có thông tin nguời nhận",
  BREAK_SHIP: "Hàng bị hỏng trong quá trình vận chuyển",
  CANNOT_CONTACT_BIKE: "Tôi không liên lạc được với khách hàng",
  CANNOT_FIND_SHOP_BIKE: "Tôi không tìm thấy địa chỉ khách hàng",
  REJECT_SHIPPER_BIKE: "Admin huỷ giúp tôi chuyến đi",
  WRONG_LOCATION: "Ứng dụng không cập nhật đúng vị trí",
  NOT_FOUND_SHIPPER: "Đặt lâu không có tài xế nhận",
  PROMOTE: "Không nhập được mã khuyến mãi",
  ERROR: "Ứng dụng bị lỗi",
  UNIFORM: "Tài xế không mặc đồng phục khi nhận đơn",
  SHIPPER_REJECT: "Tài xế báo huỷ đơn hàng",
  ATTITUDE: "Tài xế có thái độ không chuyên nghiệp",
  SHIPPER_REJECT_PROMOTE: "Tài xế từ chối nhận đơn hàng khuyến mãi",
  PHOT: "Báo phốt",
  BLOCK: "Hỗ trợ mở tài khoản",
  CHARGE: "Tôi gặp vấn đề nạp Coints",
  SSM: "Chưa được cộng tiền SSM",
  CREATE_PRODUCT: "Cần hỗ trợ tạo sản phẩm, chỉnh sửa cửa hàng",
 },

 RATING_REASON: {
  ATTITUDE: "Thái độ không thiện chí",
  DELAY: "Giao lâu",
  BEHAVIOR: "Giao tiếp",
  BREAK: "Hỏng hàng",
  EXCELLENT: "Chuyên nghiệp",
  FAST: "Siêu tốc",
  FRIENDLY: "Thân thiện",
  SAFE: "Cẩn thận",
  POLITE: "Lịch sự",
  ENTHUSIASM: "Nhiệt tình",
  GET_MORE_MONEY: "Gian lận",
  INCORRECT_SHIPPER: "Không đúng tài xế",
  WRONG_ORIGIN: "Sai điểm đón",
  GOOD: "Thiện chí",
  NOT_ENOUGH_INFO: "Sai thông tin",
 },

 REPORT_ORDER_REASON: {
  SHOP: {
   //index=orderStatus
   CANNOT_CONTACT_SHOP: ["", ""],
   CANNOT_TAKE_ORDER: [""],
   WRONG_INFOR: [""],
   CANNOT_FIND_ADDRESS: [""],
   DELAY_ARRIVE: ["", "Tôi đã đợi lâu mà Tài xế chưa tới lấy hàng"],
   FORGET_UPDATE_ARRIVED: ["", "Tài xế quên chưa cập nhật trạng thái đã lấy hàng"],
   CANNOT_CONTACT_SHIPPER: ["", "Tôi không liên lạc được với Tài xế"],
   DELAY_DELIVER: ["", "", "Khách đợi lâu mà chưa nhận được hàng"],
   FORGET_UPDATE_DONE: ["", "", "Tài xế quên chưa cập nhật đã giao xong đơn hàng"],
   AUTO_DONE: ["", "", "Tài xế tự ý cập nhật hoàn thành đơn hàng"],
   SHIPPER_CHEAT_MONEY: ["", "", "Tài xế thu thêm tiền của khách hàng"],
   CANNOT_CONTACT_CUSTOMER: [""],
  },

  SHIPPER: {
   //index=orderStatus
   CANNOT_CONTACT_SHOP: ["", "Tôi không liên hệ được với người đăng đơn"],
   CANNOT_TAKE_ORDER: ["", "Tôi không lấy được hàng"],
   WRONG_INFOR: ["", "Shop đăng sai (thiếu) thông tin đơn hàng", "Tôi không tìm được địa chỉ của khách hàng"],
   CANNOT_FIND_ADDRESS: ["", "Tôi không tìm được địa chỉ của Shop"],
   DELAY_ARRIVE: [""],
   FORGET_UPDATE_ARRIVED: [""],
   CANNOT_CONTACT_SHIPPER: [""],
   DELAY_DELIVER: [""],
   FORGET_UPDATE_DONE: [""],
   AUTO_DONE: [""],
   SHIPPER_CHEAT_MONEY: [""],
   CANNOT_CONTACT_CUSTOMER: ["", "", "Tôi không liên lạc được với khách hàng"],
  },
 },

 SHOP_INFO: {
  HEED: {
   NONE: "",
   AUTHEN_REQUIRED_SHOP: "Shop cần xác thực",
   POTENTIAL_SHOP: "Shop tiềm năng",
   NEED_PAY_ATENTION_SHOP: "Cần lưu ý phốt",
   NEED_PAY_MORE_ATENTION_SHOP: "Lưu ý thêm",
   DOUBT_CHEAT_SHOP: "Nghi ngờ phốt",
   INTENDED_CHEAT_SHOP: "Phốt",
  },
 },

 REGION: {
  hn: "Hà Nội (TP)",
  hcm: "Hồ Chí Minh (TP)",
  "vietnam:angiang": "An Giang",
  "vietnam:bariavungtau": "Bà Rịa-Vũng Tàu",
  "vietnam:baclieu": "Bạc Liêu",
  "vietnam:backan": "Bắc Kạn",
  "vietnam:bacgiang": "Bắc Giang",
  "vietnam:bacninh": "Bắc Ninh",
  "vietnam:bantre": "Bến Tre",
  "vietnam:binhduong": "Bình Dương",
  "vietnam:benhdinh": "Bình Định",
  "vietnam:binhphuoc": "Bình Phước",
  "vietnam:binhthuan": "Bình Thuận",
  "vietnam:camau": "Cà Mau",
  "vietnam:caobang": "Cao Bằng",
  "vietnam:cantho": "Cần Thơ (TP)",
  "vietnam:danang": "Đà Nẵng (TP)",
  "vietnam:daklak": "Đắk Lắk",
  "vietnam:daknong": "Đắk Nông",
  "vietnam:dienbien": "Điện Biên",
  "vietnam:dongnai": "Đồng Nai",
  "vietnam:dongthap": "Đồng Tháp",
  "vietnam:gialai": "Gia Lai",
  "vietnam:hagiang": "Hà Giang",
  "vietnam:hanam": "Hà Nam",
  "vietnam:hatay": "Hà Tây",
  "vietnam:hatinh": "Hà Tĩnh",
  "vietnam:haiduong": "Hải Dương",
  "vietnam:haiphong": "Hải Phòng (TP)",
  "vietnam:hoabinh": "Hòa Bình",
  "vietnam:haugiang": "Hậu Giang",
  "vietnam:hungyen": "Hưng Yên",
  "vietnam:khanhhoa": "Khánh Hòa",
  "vietnam:kiengiang": "Kiên Giang",
  "vietnam:kontum": "Kon Tum",
  "vietnam:laichau": "Lai Châu",
  "vietnam:laocai": "Lào Cai",
  "vietnam:langson": "Lạng Sơn",
  "vietnam:lamdong": "Lâm Đồng",
  "vietnam:longan": "Long An",
  "vietnam:namdinh": "Nam Định",
  "vietnam:nghean": "Nghệ An",
  "vietnam:ninhbinh": "Ninh Bình",
  "vietnam:ninhthuan": "Ninh Thuận",
  "vietnam:phutho": "Phú Thọ",
  "vietnam:phuyen": "Phú Yên",
  "vietnam:quangbinh": "Quảng Bình",
  "vietnam:quangnam": "Quảng Nam",
  "vietnam:quangngai": "Quảng Ngãi",
  "vietnam:quangninh": "Quảng Ninh",
  "vietnam:quangtri": "Quảng Trị",
  "vietnam:soctrang": "Sóc Trăng",
  "vietnam:sonla": "Sơn La",
  "vietnam:tayninh": "Tây Ninh",
  "vietnam:thaibinh": "Thái Bình",
  "vietnam:thainguyên": "Thái Nguyên",
  "vietnam:thanhhoa": "Thanh Hóa",
  "vietnam:thuathienhue": "Thừa Thiên – Huế",
  "vietnam:tiengiang": "Tiền Giang",
  "vietnam:travinh": "Trà Vinh",
  "vietnam:tuyenquang": "Tuyên Quang",
  "vietnam:vinhlong": "Vĩnh Long",
  "vietnam:vinhphuc": "Vĩnh Phúc",
  "vietnam:yenbai": "Yên Bái",
  "vietnam:hungyen-khoaichau": "Hưng Yên - Khoái Châu",
  "vietnam:hungyen-vangiang": "Hưng Yên - Văn Giang",
  "vietnam:hungyen-vanlam": "Hưng Yên - Văn Lâm",
  "vietnam:hungyen-yenmy": "Hưng Yên - Yên Mỹ",
  "vietnam:hungyen-myhao": "Hưng Yên - Mỹ Hào",
  "vietnam:hungyen-phucu": "Hưng Yên - Phù Cừ",
  "vietnam:hungyen-tienlu": "Hưng Yên - Tiên Lữ",
  "vietnam:hungyen-kimdong": "Hưng Yên - Kim Động",
  "vietnam:haiduong-chilinh": "Hải Dương - Chí Linh",
  "vietnam:hungyen-anthi": "Hưng Yên - Ân Thi",
  "vietnam:bacninh-tuson": "Bắc Ninh - Từ Sơn",
 },

 AUTHEN_RIDER_STATUS: {
  PREPARING: 0,
  CHECKING: 1,
  REJECTED: -1,
  WAIT_FOR_APPROVE: 2,
  UNAPPROVED: -2,
  APPROVED: 3,
 },

 AUTHEN_RIDER_TYPE: {
  PREPARE: 0,
  START_AUTHEN: 1,
  REJECT: -1,
  SEND_AUTHEN: 2,
  ADMIN_UNAPPROVE: -2,
  ADMIN_APPROVE: 3,
  ADMIN_REQUEST_RECHECK: 4,
 },

 AUTHEN_RIDER_STATUS_TRANS: {
  0: {
   title: "Chuẩn bị",
   color: "#e31b36",
  },
  1: {
   title: "Đang kiểm tra",
   color: "#e8a023",
  },
  "-1": {
   title: "Từ chối",
   color: "#e31b36",
  },
  2: {
   title: "Chờ duyệt",
   color: "#1b43e3",
  },
  "-2": {
   title: "Từ chối duyệt",
   color: "#e31b36",
  },
  3: {
   title: "Đã duyệt",
   color: "#23e844",
  },
 },

 AUTHEN_RIDER_TYPE_TRANS: {
  0: {
   title: "Chuẩn bị",
   color: "#e31b36",
  },
  1: {
   title: "Bắt đầu kiểm tra",
   color: "#e8a023",
  },
  "-1": {
   title: "Từ chối",
   color: "#e31b36",
  },
  2: {
   title: "Gửi yêu cầu kiểm tra",
   color: "#1b43e3",
  },
  "-2": {
   title: "Admin từ chối duyệt",
   color: "#e31b36",
  },
  3: {
   title: "Admin duyệt",
   color: "#23e844",
  },
  4: {
   title: "Admin yêu cầu kiểm tra lại",
   color: "#23e844",
  },
 },
}
