export default {
 CODE: {
  SUCCESS: 200,
  FAIL: 300,
  WRONG_PARAMS: 400,
  ACCESS_DENINED: 403,
  SYSTEM_ERROR: 500,
  TOKEN_EXPIRE: 1993,
  ORDER_EXPIRE: 1999,
 },
 JOB_STATUS: {
  FREE: 0,
  DOING: 1,
  DONE: 2,
  WAITING: 3,
  WAIT_FOR_ACTION: 4,
 },
 ORDER_STATUS: {
  WAIT_FOR_PAYMENT: -1,
  EXECUTING: 0,
  DONE: 1,
  REJECTED: 2,
  FAILED: 3,
 },
 ORDER_CLEAN_STATUS: {
  WAIT_FOR_PAYMENT: -1,
  EXECUTING: 0,
  DONE: 1,
  REJECTED: 2,
  FAILED: 3,
 },
 ORDER_JOB_STATUS: {
  WAIT_FOR_CONFIRM: -3,
  PENDING: -2,
  WAIT_FOR_PAYMENT: -1,
  FINDING: 0,
  FOUND_CAREGIVER: 1,
  MOVING: 2,
  EXECUTING: 3,
  DONE: 4,
  REJECTED: 5,
  CAN_NOT_FIND_CAREGIVER: 6,
 },
 ORDER_CLEAN_JOB_STATUS: {
  WAIT_FOR_CONFIRM: -3,
  PENDING: -2,
  WAIT_FOR_PAYMENT: -1,
  FINDING: 0,
  FOUND_STAFF: 1,
  MOVING: 2,
  EXECUTING: 3,
  DONE: 4,
  REJECTED: 5,
  CAN_NOT_FIND_STAFF: 6,
 },
 ORDER_LOG: {
  WAIT_FOR_PAYMENT: -1,
  PAY: 0,
  CREATE: 1,
  DONE_JOBS: 2,
  REJECT: 3,
  RETRY: 4,
  FAIL: 5,
 },

 MEMBER_TYPE: {
  SHIPPER: 0,
  ADMIN: 1,
  CUSTOMER: 2,
  TICKBOX: 3,
  CAREGIVER: 4,
 },

 BLOCK_LOGS_RETRAINING: {
  NONE: 0,
  BIKE: 1,
  CAR: 2,
  HIRE_DRIVER: 3,
 },

 JOB_TYPE: {
  CREATE: 0,
  GENERAL_FEEDBACK: 1,
  ORDER_CANCEL_FEEDBACK: 2,
  REPORT_ORDER_FEEDBACK: 3,
  OS_NEED_TAKING: 4,
  OS_NEED_DONE: 5,
  OS_AFTER_CANCEL: 6,
  OS_CANNOT_FOUND_SHIPPER: 27,
  OS_NEED_CONTACT: 7,
  OS_NEW_SHOP: 8,
  OS_NOT_AUTHEN: 9,
  RATING: 10,
  RATING_UNIFORM: 11,
  OS_NEED_TRAINING: 12,
  OS_NEED_TRAINING_PROMOTE: 13,
  SHIPPER_DONE_PROMOTE: 14,
  SHIPPER_DONE_PROMOTE_BIKE: 15,
  RATING_BIKE: 16,
  OB_NEED_TAKING: 17,
  OB_NEED_DONE: 18,
  OB_AFTER_CANCEL: 19,
  OB_NEED_CONTACT: 20,
  OB_NEED_TRANING: 21,
  LOYALTY_SHOPING: 22,
  OS_NEED_TRAINING_HUB: 23,
  OS_NEED_TRAINING_CART: 24,
  RATING_CUSTOMER: 25,
  CHEAT_ORDER: 26,
  CHECK_UNIFORM: 28,
  TICKBOX_SELF_DELIVERY_DONE: 29,
  OHD_NEED_CONTACT: 37,
  OHD_NEED_UPDATE: 38,
  OHD_NEED_DONE: 39,
  OHD_REJECTED: 40,
  CARE_ORDER_REJECTED: 41,
  CARE_JOB_NEED_CONTACT: 42,
  CARE_JOB_NEED_DONE: 43,
  CARE_JOB_LATE: 44,
  CARE_JOB_NEED_MOVING: 45,
  CARE_JOB_NEED_CONFIRM: 46,
  RATING_HEYCARE: 47,
  TRAINING_PROMOTE_HEYCARE: 48,
  CLEAN_ORDER_REJECTED: 49,
  CLEAN_JOB_NEED_CONTACT: 50,
  CLEAN_JOB_NEED_DONE: 51,
  CLEAN_JOB_LATE: 52,
  CLEAN_JOB_NEED_MOVING: 53,
  CLEAN_JOB_NEED_CONFIRM: 54,
  RATING_HEYCLEAN: 55,
  TRAINING_PROMOTE_HEYCLEAN: 56,
  STAFF_DONE_PROMOTE_HEYCARE: 57,
  STAFF_DONE_PROMOTE_HEYCLEAN: 58,
 },

 FEEDBACK_REASON: {
  CANNOT_CALL: "Tôi không liên lạc được với tài xế",
  DELAY: "Tài xế giao hàng chậm",
  NOT_ARRIVE: "Tài xế không đến lấy hàng",
  CHEAT_MONEY: "Tài xế thu thêm tiền",
  NOT_FOUND: "Tôi không tìm được tài xế cho đơn hàng",
  CANNOT_CONTACT: "Tôi không liên lạc được với tài xế/shop",
  WRONG_UPDATE: "Tài xế cập nhật sai trạng thái đơn hàng",
  REJECT_SHOP: "Tôi không huỷ được đơn hàng",
  WRONG_DISTANCE: "Đơn hàng bị tính sai khoảng cách",
  WRONG_MONEY: "Đơn hàng sai giá",
  DENY: "Khách không nhận đơn hàng",
  BREAK: "Hàng của tôi bị hỏng trong quá trình vận chuyển",
  PAYMENT: "Tôi gặp vấn đề khi thanh toán đơn hàng",
  NOT_ARRIVE_BIKE: "Tài xế không đến đón tôi",
  NOT_FOUND_BIKE: "Tôi không tìm được tài xế",
  REJECT_SHOP_BIKE: "Tôi không huỷ được chuyến đi",
  WRONG_DISTANCE_BIKE: "Chuyến đi bị tính sai khoảng cách",
  WRONG_MONEY_BIKE: "Chuyến đi sai giá",
  PAYMENT_BIKE: "Tôi gặp vấn đề khi thanh toán chuyến đi",
  CANNOT_FIND_SHOP: "Tôi không tìm thấy địa chỉ shop",
  REJECT_SHIPPER: "Admin huỷ giúp tôi đơn hàng",
  PENDING: "Hỗ trợ chuyển trạng thái chờ giao",
  NOT_FOUND_RECEIVER: "Tôi không có thông tin nguời nhận",
  BREAK_SHIP: "Hàng bị hỏng trong quá trình vận chuyển",
  CANNOT_CONTACT_BIKE: "Tôi không liên lạc được với khách hàng",
  CANNOT_FIND_SHOP_BIKE: "Tôi không tìm thấy địa chỉ khách hàng",
  REJECT_SHIPPER_BIKE: "Admin huỷ giúp tôi chuyến đi",
  WRONG_LOCATION: "Ứng dụng không cập nhật đúng vị trí",
  NOT_FOUND_SHIPPER: "Đặt lâu không có tài xế nhận",
  PROMOTE: "Không nhập được mã khuyến mãi",
  ERROR: "Ứng dụng bị lỗi",
  UNIFORM: "Tài xế không mặc đồng phục khi nhận đơn",
  SHIPPER_REJECT: "Tài xế báo huỷ đơn hàng",
  ATTITUDE: "Tài xế có thái độ không chuyên nghiệp",
  SHIPPER_REJECT_PROMOTE: "Tài xế từ chối nhận đơn hàng khuyến mãi",
  PHOT: "Báo phốt",
  BLOCK: "Hỗ trợ mở tài khoản",
  CHARGE: "Tôi gặp vấn đề nạp Coints",
  SSM: "Chưa được cộng tiền SSM",
  CREATE_PRODUCT: "Cần hỗ trợ tạo sản phẩm, chỉnh sửa cửa hàng",
 },

 RATING_REASON: {
  ATTITUDE: "Thái độ",
  DELAY: "Giao lâu",
  BEHAVIOR: "Giao tiếp",
  BREAK: "Hỏng hàng",
  EXCELLENT: "Chuyên nghiệp",
  FAST: "Siêu tốc",
  FRIENDLY: "Thân thiện",
  SAFE: "Cẩn thận",
  POLITE: "Lịch sự",
  ENTHUSIASM: "Nhiệt tình",
  GET_MORE_MONEY: "Gian lận",
  INCORRECT_SHIPPER: "Không đúng tài xế",
  WRONG_ORIGIN: "Sai điểm đón",
  GOOD: "Thiện chí",
  LATE: "Đến muộn",
  CARELESS: "Cẩu thả",
  NOT_ENOUGH_INFO: "Sai thông tin",
 },

 JOB_TRANS_TYPE: {
  "-3": "Chỉ định CSV",
  "-2": " Chờ",
  "-1": " Chờ thanh toán",
  0: "Tìm kiếm",
  1: "Tạo ca làm việc",
  2: "Nhận ca",
  3: "Di chuyển",
  4: "Bắt đầu ca",
  5: "Kết thúc ca",
  6: "Hủy ca",
  7: "Tìm lại ca",
  8: "Không có CSV",
  9: "Gán CSV",
  10: "Đổi trưởng nhóm",
  11: "Thay đổi thời gian làm việc",
 },
 JOB_CLEAN_TRANS_TYPE: {
  "-3": "Chỉ định người giúp việc",
  "-2": " Chờ",
  "-1": " Chờ thanh toán",
  0: "Tìm kiếm",
  1: "Tạo ca giúp việc",
  2: "Nhận ca",
  3: "Di chuyển",
  4: "Bắt đầu ca",
  5: "Kết thúc ca",
  6: "Hủy ca",
  7: "Tìm lại ca",
  8: "Không có người giúp việc",
  9: "Gán người giúp việc",
 },
 ORDER_TRANS_TYPE: {
  "-1": " Chờ thanh toán",
  0: "Thanh toán",
  1: "Tạo đơn chăm sóc",
  2: "Hoàn thành",
  3: "Hủy",
  4: "Tìm lại",
  5: "Không có CSV",
 },

 ORDER_CLEAN_TRANS_TYPE: {
  "-1": " Chờ thanh toán",
  0: "Thanh toán",
  1: "Tạo đơn giúp việc",
  2: "Hoàn thành",
  3: "Hủy",
  4: "Tìm lại",
  5: "Không có người giúp việc",
 },

 CMS_CONFIG_TYPE: {
  BLOCK_REQ_CONFIG: 9,
 },
 MEMBER_LOG_RESULT: {
  NOTE: null,
  UNIFORM_CHECK: {
   OBEY: "Có đồng phục",
   NOT_OBEY: "Không có đồng phục",
  },
  ACCOUNT_CHECK: {
   OWNER: "Chính chủ",
   NOT_OWNER: "Không chính chủ",
  },
 },
}
